### ISSUE TITLE
alts add/confirm system unclear, help doesn't explain how to do it

### ISSUE THREAD

**Issue by profnagol** [Nadybot/Nadybot#140]

**Comment by Nadyita** [comment]
@profnagol Okay, so what did you type that didn't behave as expected and where would you expect the documentation to be?
Like… did you try `!alts <name>` or `!alts add <name>` and what would you wish to show?

**Comment by profnagol** [comment]
orgmate of mine added an alt out of my org, the alts show as unconfirmed, but there is no way to confirm it, the help doesn't show a command for that in !help alts

**Comment by Nadyita** [comment]
Ah, I understand. I will add a part to the documentation in `help alts` that will explain alt confirmation.
In the meantime, just log onto that alt and they will receive a message asking to confirm the alt.
