### ISSUE TITLE
updateitems command fails?

### ISSUE THREAD

**Issue by Bengelator** [Nadybot/Nadybot#176]
Dear Nady,
i have following problem:
[ INFO] [Inc. Discord Msg.] Bengele#9780: updateitems
[ERROR] Could not find latest items db aodb on server

[ERROR] Could not find latest items db buffs on server

[ERROR] Could not find latest items db item_buffs on server

[ERROR] Could not find latest items db item_types on server

[ERROR] Could not find latest items db item_groups on server

[ERROR] Could not find latest items db item_group_names on server

Thank you for your amazing work

**Comment by Nadyita** [comment]
This is, because 5.1 moved to CSV files instead of SQL.
5.1 will have manual DB updates, 5.1.1 will then have fully automated ones again.
