### ISSUE TITLE
Discordbot goes offline

### ISSUE THREAD

**Issue by Bengelator** [Nadybot/Nadybot#177]
Hi Nady,
i hope for a solution thats more stable when you are using the docker

Thanks for your amazing work

**Comment by Nadyita** [comment]
We've had a bot run for 1 months straight on discord via docker and not had any issues. At this point, we can clearly rule out that it's Nadybot's fault.
If that ever happens again, can you please check if `!whois` still works? A log would be nice from this

**Comment by Nadyita** [comment]
Apparently no longer an issue
