### ISSUE TITLE
[ITEMS_MODULE] !boss command errors

### ISSUE THREAD

**Issue by zewm** [Nadybot/Nadybot#38]
**Player:** !boss legchopper

**Nadybot:** There was an error executing your command: Argument 1 passed to Nadybot\Core\Text::makeImage() must be of the type int, null given, called in C:\Users\User\Desktop\bundle (2) - Copy\src\Modules\ITEMS_MODULE\BosslootController.php on line 107

**Comment by Nadyita** [comment]
Fixed in [this commit](https://github.com/Nadybot/Nadybot/commit/0fd6fc2236ad4f6cbc39f61460f7c907e5eb9ca2).
