### ISSUE TITLE
config file throw errors with latest repository

### ISSUE THREAD

**Issue by profnagol** [Nadybot/Nadybot#383]
with php 8

thrown in /*****/Acfbot2/vendor/spatie/data-transfer-object/src/DataTransferObjectError.php on line 15
PHP Fatal error:  Uncaught Spatie\DataTransferObject\DataTransferObjectError: Public properties `my_guild`, `SuperAdmin`, `DB Type`, `DB Name`, `DB Host`, `DB username`, `DB password`, `show_aoml_markup`, `cachefolder`, `htmlfolder`, `datafolder`, `logsfolder`, `default_module_status`, `enable_console_client`, `enable_package_module`, `use_proxy`, `proxy_server`, `proxy_port`, `module_load_paths` not found on Nadybot\Core\ConfigFile in /*****/Acfbot2/vendor/spatie/data-transfer-object/src/DataTransferObjectError.php:15
Stack trace:
#0 /*****/Acfbot2/vendor/spatie/data-transfer-object/src/DataTransferObject.php(89): Spatie\DataTransferObject\DataTransferObjectError::unknownProperties()
#1 /*****/Acfbot2/src/Core/ConfigFile.php(155): Spatie\DataTransferObject\DataTransferObject->__construct()
#2 /*****/Acfbot2/src/Core/ConfigFile.php(167): Nadybot\Core\ConfigFile->__construct()
#3 /*****/Acfbot2/src/Core/BotRunner.php(352): Nadybot\Core\ConfigFile::loadFromFile()
#4 /*****/Acfbot2/src/Core/BotRunner.php(242): Nadybot\Core\BotRunner->getConfigFile()
#5 /*****/Acfbot2/main.php(29): Nadybot\Core\BotRunner->run()
#6 {main}

**Comment by Nadyita** [comment]
@profnagol That means your config file is broken, If you cannot find the error, feel free to copy the config without password. Or better yet, join our Discord server :+1:

**Comment by profnagol** [comment]
I remade the config file from scratch, using the sample file, still no go, please provide a sample config file that works

**Comment by profnagol** [comment]
I don't think this should be closed as there is no way to actually start from scratch a fresh install and make it operate, the sample config file, doesn't work, at all.
