### ISSUE TITLE
feature request: add a package for raspbian

### ISSUE THREAD

**Issue by olafrose** [Nadybot/Nadybot#389]
i'd love to run this on one of my raspberries but would love the convenience of using apt

**Comment by Nadyita** [comment]
@olafrose I just checked, and the package is marked as architectural independent. Can you try installing it?

**Comment by Nadyita** [comment]
Oka, follow-up question: rpi3 or rpi4? Raspbian? I couldn't get PHP8 from any official sources for rpi3 Raspbian, but if ou have an rpi4 with that, it should be possible. Best is to contact me in Discord, so I can explain how

**Comment by Nadyita** [comment]
@olafrose Fine, I figured it out myself.

See [this Wiki page](https://github.com/Nadybot/Nadybot/wiki/Packages#raspbian-based-on-debian-10-or-11-pi3-and-pi4-32bit--64bit) how to run Nadybot on a Pi by using the Ubuntu packages. I tested this on 32bit + 64bit, on Pi3 and Pi4 and based on Debian10 and Debian11.
