### ISSUE TITLE
Full auto calculation is incorrect.

### ISSUE THREAD

**Issue by KelticDanor** [Nadybot/Nadybot#478]
I've been doing a bunch of tests with Conci and found the full auto calculation is off a little bit.

This line....
https://github.com/Nadybot/Nadybot/blob/de9e3b2c8d2f91df87c614a3d9f91bc16c2eacf2/src/Modules/SKILLS_MODULE/SkillsController.php#L421

Needs to be changed to...
`if ($faRecharge == 0) { $faRecharge = 1000; }`
`$myFullAutoRecharge = (int)floor(($rechargeTime * 40) + ($faRecharge / 100) - ($faSkill / 25) + $attackTime);`

This is consistent with the burst formula and will return the correct values as per the below. The default value of the full auto cycle is 1000 as per tests with the Hellfury done on discord a while back.

**BigBurger Testing - Incorrect Current Values**
> (int)round((1.0 * 40) + (3400 / 100) - (1557 / 25) + round(1.3 - 1)); = 12
> (int)round((1.0 * 40) + (3400 / 100) - (1575 / 25) + round(1.3 - 1)); = 11
> (int)round((1.0 * 40) + (3400 / 100) - (1582 / 25) + round(1.3 - 1)); = 11
> (int)round((1.0 * 40) + (3400 / 100) - (1583 / 25) + round(1.3 - 1)); = 11

**BigBurger Testing - Corrected Values**
> (int)floor((1.0 * 40) + (3400 / 100) - (1557 / 25) + 1.3); = 13 CORRECT
> (int)floor((1.0 * 40) + (3400 / 100) - (1575 / 25) + 1.3); = 12 CORRECT
> (int)floor((1.0 * 40) + (3400 / 100) - (1582 / 25) + 1.3); = 12 CORRECT
> (int)floor((1.0 * 40) + (3400 / 100) - (1583 / 25) + 1.3); = 11 CORRECT

**Envy Testing - Incorrect Current Values**
> (int)round((1.2 * 40) + (6000 / 100) - (2390 / 25) + round(1.2 - 1)); = 12
> (int)round((1.2 * 40) + (6000 / 100) - (2425 / 25) + round(1.2 - 1)); = 11
> (int)round((1.2 * 40) + (6000 / 100) - (2430 / 25) + round(1.2 - 1)); = 11
> (int)round((1.2 * 40) + (6000 / 100) - (2431 / 25) + round(1.2 - 1)); = 11

**Envy Testing - Corrected Values**
> (int)floor((1.2 * 40) + (6000 / 100) - (2390 / 25) + 1.2); = 13 CORRECT
> (int)floor((1.2 * 40) + (6000 / 100) - (2425 / 25) + 1.2); = 12 CORRECT
> (int)floor((1.2 * 40) + (6000 / 100) - (2430 / 25) + 1.2); = 12 CORRECT
> (int)floor((1.2 * 40) + (6000 / 100) - (2431 / 25) + 1.2); = 11 CORRECT

There are more details and data points available on the AO discord if needed.

**Comment by Nadyita** [comment]
Interesting. I've done lots of calculations with Patate-1 back then, and our measurements showed that the `round($attackTime - 1)` was crucial. Can you give me a link to these tests, I'd like to take a look myself. I don't want to change the formula without being 100% sure

**Comment by KelticDanor** [comment]
There are some more here related to BigBurger though I can get more if you like.
https://discord.com/channels/350012232433795077/350012232433795078/1270982970752241738

Also here is charts from Conci related to the Envy.
Graphed new figures: https://discord.com/channels/350012232433795077/468639745812201472/1271020561098604606
Graphed old figures: https://discord.com/channels/350012232433795077/468639745812201472/1271022615678554176

Also been finding a small inaccuracy regarding the Burst and Fast Attack calculations regarding the skill necessary to cap them being higher than seems to be required. I have some data here but it requires further testing.
https://discord.com/channels/350012232433795077/350012232433795078/1271032789856288811

Not sure how to fix it but presumably if the full auto calc needs tweaks the skillcap one would need a tweak as well.
https://github.com/Nadybot/Nadybot/blob/de9e3b2c8d2f91df87c614a3d9f91bc16c2eacf2/src/Modules/SKILLS_MODULE/SkillsController.php#L787

**Comment by KelticDanor** [comment]
Just in addition to the above there has been further discussion in the all images channel of AO discord as per....
https://discord.com/channels/350012232433795077/468639745812201472/1271216061362081824

Conci also did some test with wireshark and it looks like AO doesn't worry about the decimals which is why all the cooldown calculations have floor() which is great news as it confirms that having CD to get down to 6.99 for fast attack for example is enough to get 6 second CD.

Tinker has updated the items site to match the new figures/math for fast attack, fling shot, burst, full auto and aimed shot so they are all consistent with links to it here: https://github.com/TheTinkeringIdiot/Tinkerplants/blob/main/tinkertools/views.py
And of course can see the new figures in the items pages. Oh this includes adding the default values of 1000 for burst and full auto cycle for weapons that don't have them set such as the Replica Hellfury.

I'm happy to do some more testing as you like or any other examples.

**Comment by Nadyita** [comment]
I'll take a closer look once I have some more time. Thanks for all the work. I've been gone from the game for too long to be able to judge whether your calculations are better or not, so I'm contacting the person who helped me with the Fling Shot formula back then. I hope it won't take too long to validate this.
Thanks again for reporting it and gathering all that data :)

**Comment by Nadyita** [comment]
Are you able to test the development branch and give feedback, if this fixes things?

**Comment by KelticDanor** [comment]
I didn't/don't have a good way to test the dev branch but Keex is giving me a hand with that, There's a few things to cover but from what I gather he's been in touch already. 😄 I'll work with him and I imagine he'll get back to you with the goods.
