### ISSUE TITLE
"!whatbuffs Heavy Weapons" command can't be used

### ISSUE THREAD

**Issue by keex74** [Nadybot/Nadybot#486]
Tested with system: 
> Nadybot: 6.2.9@stable
> PHP: 8.2.20
> Event loop: Amp NativeDriver using ParallelDriver filesystem
> OS: Linux 6.1.0-rpi7-rpi-v8 aarch64
> Database: sqlite

The command `whatbuffs Heavy Weapons` seems to interpret the `Weapons` part as the type and not as part of the skill.
The bot responds with:
> No items found of type Weapon that buff Heavy Weapons.

Hence I think the command can't be used for this skill at the moment.
A workaround may be to add an alias for the skill, like `hw`.

Cheers!
Keex

**Comment by keex74** [comment]
Oh, so, I just noticed that it's not as broken as it seemed. If I manually add another modifier like `chest` it works. But clicking on the skill in the `whatbuffs` list executes the above command instead of showing the list of possible positions like usual. :-)

**Comment by Nadyita** [comment]
I'll see if I can properly fix it in N7, but the current N6 has no means to solve it easily. Sadly.

**Comment by keex74** [comment]
thanks Nady! :-) I don't think it's of the highest priority - you can still use it with the slots, and HW isn't the most sought-after skill :D
