### ISSUE TITLE
Discord gateway reconnection handling

### ISSUE THREAD

**Issue by Gelbpunkt** [Nadybot/Nadybot#51]
There seems to be an issue where the Discord gateway client disconnects after several days, which might be:
* Cloudflare
* Opcodes where resuming isn't allowed

We should try to reproduce this and investigate a side-issue where memory allocation in PHP seems to fail in the gateway module when memory is free. Could be a memory leak?

TODO:
* Proper reconnection backoff with max 5 retries
* Log websocket closing?

**Comment by Nadyita** [comment]
@Gelbpunkt , can we consider this done? Haven't seen any connection issues anymore.

**Comment by Gelbpunkt** [comment]
It should be fine now, any issues occuring past this point are out of our control
